logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    com.mycompany.microservice: DEBUG
    org.springframework.security: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
  jackson:
    serialization:
      indent-output: true
  cloud:
    config:
      uri: http://admin:${jhipster.registry.password}@localhost:8761/config
      name: microservice
      profile: dev
      label: main
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5433/microservice
    username: microservice
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  liquibase:
    contexts: dev, faker
  security:
    oauth2:
      resourceserver:
        jwt:
          # Keycloak JWT validation
          issuer-uri: http://localhost:9080/realms/jhipster
          jwk-set-uri: http://localhost:9080/realms/jhipster/protocol/openid-connect/certs

server:
  port: 8081
  forward-headers-strategy: native

jhipster:
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 100
  registry:
    password: admin
  security:
    content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:"
    authentication:
      jwt: {}
